2022-08-17 00:10:44,108 INFO    MainThread:64667 [internal.py:wandb_internal():90] W&B internal server running at pid: 64667, started at: 2022-08-17 00:10:44.106414
2022-08-17 00:10:44,145 INFO    WriterThread:64667 [datastore.py:open_for_write():75] open: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20220817_001041-1mjpbj6b/run-1mjpbj6b.wandb
2022-08-17 00:10:44,145 DEBUG   HandlerThread:64667 [handler.py:handle_request():141] handle_request: run_start
2022-08-17 00:10:44,182 DEBUG   HandlerThread:64667 [meta.py:__init__():35] meta init
2022-08-17 00:10:44,182 DEBUG   HandlerThread:64667 [meta.py:__init__():49] meta init done
2022-08-17 00:10:44,182 DEBUG   HandlerThread:64667 [meta.py:probe():209] probe
2022-08-17 00:10:44,199 DEBUG   HandlerThread:64667 [meta.py:_setup_git():199] setup git
2022-08-17 00:10:44,321 DEBUG   HandlerThread:64667 [meta.py:_setup_git():206] setup git done
2022-08-17 00:10:44,321 DEBUG   HandlerThread:64667 [meta.py:_save_pip():53] save pip
2022-08-17 00:10:44,324 DEBUG   HandlerThread:64667 [meta.py:_save_pip():67] save pip done
2022-08-17 00:10:44,325 DEBUG   HandlerThread:64667 [meta.py:_save_conda():74] save conda
2022-08-17 00:11:11,236 WARNING MainThread:64667 [internal.py:wandb_internal():153] Internal process interrupt: 1
2022-08-17 00:11:11,527 WARNING MainThread:64667 [internal.py:wandb_internal():153] Internal process interrupt: 2
2022-08-17 00:11:11,527 ERROR   MainThread:64667 [internal.py:wandb_internal():156] Internal process interrupted.
2022-08-17 00:11:11,648 DEBUG   HandlerThread:64667 [meta.py:_save_conda():84] save conda done
2022-08-17 00:11:11,648 DEBUG   HandlerThread:64667 [meta.py:probe():247] probe done
2022-08-17 00:11:12,140 INFO    SenderThread:64667 [sender.py:finish():1111] shutting down sender
2022-08-17 00:11:12,174 INFO    WriterThread:64667 [datastore.py:close():279] close: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20220817_001041-1mjpbj6b/run-1mjpbj6b.wandb
2022-08-17 00:11:12,785 INFO    HandlerThread:64667 [handler.py:finish():806] shutting down handler
2022-08-17 00:11:12,786 INFO    MainThread:64667 [internal.py:handle_exit():80] Internal process exited
