2022-08-07 00:37:13,691 INFO    MainThread:1717847 [internal.py:wandb_internal():90] W&B internal server running at pid: 1717847, started at: 2022-08-07 00:37:13.688893
2022-08-07 00:37:13,716 INFO    WriterThread:1717847 [datastore.py:open_for_write():75] open: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20220807_003711-2vvhwnrp/run-2vvhwnrp.wandb
2022-08-07 00:37:13,717 DEBUG   HandlerThread:1717847 [handler.py:handle_request():141] handle_request: run_start
2022-08-07 00:37:13,738 DEBUG   HandlerThread:1717847 [meta.py:__init__():35] meta init
2022-08-07 00:37:13,738 DEBUG   HandlerThread:1717847 [meta.py:__init__():49] meta init done
2022-08-07 00:37:13,738 DEBUG   HandlerThread:1717847 [meta.py:probe():209] probe
2022-08-07 00:37:13,753 DEBUG   HandlerThread:1717847 [meta.py:_setup_git():199] setup git
2022-08-07 00:37:13,860 DEBUG   HandlerThread:1717847 [meta.py:_setup_git():206] setup git done
2022-08-07 00:37:13,860 DEBUG   HandlerThread:1717847 [meta.py:_save_pip():53] save pip
2022-08-07 00:37:13,863 DEBUG   HandlerThread:1717847 [meta.py:_save_pip():67] save pip done
2022-08-07 00:37:13,865 DEBUG   HandlerThread:1717847 [meta.py:_save_conda():74] save conda
2022-08-07 00:37:20,032 WARNING MainThread:1717847 [internal.py:wandb_internal():153] Internal process interrupt: 1
2022-08-07 00:37:20,359 WARNING MainThread:1717847 [internal.py:wandb_internal():153] Internal process interrupt: 2
2022-08-07 00:37:20,359 ERROR   MainThread:1717847 [internal.py:wandb_internal():156] Internal process interrupted.
2022-08-07 00:37:20,454 DEBUG   HandlerThread:1717847 [meta.py:_save_conda():84] save conda done
2022-08-07 00:37:20,454 DEBUG   HandlerThread:1717847 [meta.py:probe():247] probe done
2022-08-07 00:37:20,720 INFO    WriterThread:1717847 [datastore.py:close():279] close: /fsx/ganayu/code/SuperShaper/wandb/offline-run-20220807_003711-2vvhwnrp/run-2vvhwnrp.wandb
2022-08-07 00:37:20,727 INFO    SenderThread:1717847 [sender.py:finish():1111] shutting down sender
2022-08-07 00:37:21,254 INFO    HandlerThread:1717847 [handler.py:finish():806] shutting down handler
2022-08-07 00:37:21,254 INFO    MainThread:1717847 [internal.py:handle_exit():80] Internal process exited
